name: "Build Check"
on:
  workflow_dispatch:
  pull_request:
  push:
jobs:
  build-check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v1
      - uses: cachix/cachix-action@v14
        with:
          name: kero0
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build --accept-flake-config .#
      - name: Diff profile
        id: diff
        run: |
          echo "# $RUNNER_OS changes" > message-body
          nix store diff-closures --accept-flake-config --derivation \
              "github:${{ github.repository }}/${{ github.event.before }}" \
              "." | sed 's/\x1b\[[0-9;]*m//g' >> message-body

      - name: Comment PR
        uses: peter-evans/create-or-update-comment@v4
        if: github.event_name == 'pull_request'
        with:
          body-path: message-body
          issue-number: ${{ github.event.pull_request.number }}
      - name: Comment Commit
        uses: peter-evans/commit-comment@v3
        if: github.event_name == 'push'
        with:
          body-path: message-body
