name: "Build Check"
permissions:
  contents: write
  pull-requests: write
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22
      - uses: cachix/cachix-action@v17
        with:
          name: kero0
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build --accept-flake-config --show-trace -L .#
      - name: Diff profile
        id: diff
        run: |
          {
            echo 'body<<EOF'
            echo "# $RUNNER_OS changes"

            nix store diff-closures --accept-flake-config --derivation \
                "github:${{ github.repository }}/${{ github.event.before }}" \
                "." | sed 's/\x1b\[[0-9;]*m//g'

            echo 'EOF'
          } >> $GITHUB_OUTPUT
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v9
        with:
          script: |
            const body = `${{ steps.diff.outputs.body }}`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });

      - name: Comment on commit
        if: github.event_name == 'push'
        uses: actions/github-script@v9
        with:
          script: |
            const body = `${{ steps.diff.outputs.body }}`;

            await github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body
            });
